name: google_map
description: A Flutter application integrating Google Maps.
publish_to: 'none' # This ensures the project isn't published to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0' # Ensure compatibility with Dart SDK versions.

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0 # Latest version of the Google Maps plugin.
  cupertino_icons: ^1.0.8 # iOS style icons for Cupertino widgets.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Provides linting rules for Flutter projects.

flutter:
  uses-material-design: true
  # Include all images in this directory.
  
